name: RoboReG
url: https://robotics-club-iit-bhu.github.io/RoboReG

exclude: [bibble, README.md, Makefile, screenshot.png]

#Base pathname for links. Uncomment this to build for deployment.
base: https://robotics-club-iit-bhu.github.io/RoboReG

# colorize code snippets with the rouge module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: members
    name: Members
  - key: technicalLead
    name: leads
  - key: technicalLead1
    name: leads1
  # - key: staff
  #   name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: mentors
    name: Mentors
  - key: members2
    name: Members
  - key: members3
    name: Members
  - key: mentors1
    name: Mentors
  - key: ancestors_0
    name: Ancestors_0
  - key: ancestors_0_1
    name: Ancestors_1
  - key: ancestor_1_0
    name: ancestor_1
  - key: ancestor_1_1
    name: Ancestor_1_1
  - key: new_joinee
    name: new_joinee
  - key: new_joinee1
    name: new_joinee1

# Number of news stories on the front page.
front_page_news: 10

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Code
    link: /code.html
  - title: RoboReG Talks
    link: /talk.html
  - title: Contact & Joining
    link: /join.html
  - title: Group's Ancestory
    link: /ancestory.html
# theme: jekyll-theme-cayman
