name: RoboReG
url: https://roboticexplorationlab.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# Base pathname for links. Uncomment this to build for deployment.
# base: /rexlab-website

# colorize code snippets with the rouge module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: members
    name: Members
  # - key: staff
  #   name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: mentors
    name: Mentors
  - key: members2
    name: Members


# Number of news stories on the front page.
front_page_news: 3

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Code
    link: /code.html
  - title: Joining
    link: /join.html
# theme: jekyll-theme-cayman
